sudo: no
language: python
install:
  - mkdir -p $PIP_WHEEL_DIR
  - pip wheel -r tests/requirements.txt codecov
  - pip install tox codecov
script:
  - tox
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR
matrix:
  include:
    - env: TOXENV=docs
    - python: 2.7
      env: TOXENV=py27-1.8
    - python: 2.7
      env: TOXENV=py27-1.9
    - python: 2.7
      env: TOXENV=py27-1.10
    - python: 2.7
      env: TOXENV=py27-1.11
    - python: 3.3
      env: TOXENV=py33-1.8
    - python: 3.4
      env: TOXENV=py34-1.8
    - python: 3.4
      env: TOXENV=py34-1.9
    - python: 3.4
      env: TOXENV=py34-1.10
    - python: 3.4
      env: TOXENV=py34-1.11
    - python: 3.4
      env: TOXENV=py34-2.0
    - python: 3.5
      env: TOXENV=py35-1.8
    - python: 3.5
      env: TOXENV=py35-1.9
    - python: 3.5
      env: TOXENV=py35-1.10
    - python: 3.5
      env: TOXENV=py35-1.11
    - python: 3.5
      env: TOXENV=py35-2.0
    - python: 3.5
      env: TOXENV=py35-master
    - python: 3.6
      env: TOXENV=py36-1.11
    - python: 3.6
      env: TOXENV=py36-2.0
    - python: 3.6
      env: TOXENV=py36-master
after_success: codecov
cache:
  directories:
    - $HOME/.wheels