language: python
install:
  - mkdir -p $PIP_WHEEL_DIR
  - pip wheel -r tests/requirements.txt codecov
  - pip install tox codecov
script:
  - tox
env:
  global:
    - PIP_WHEEL_DIR=$HOME/.wheels
    - PIP_FIND_LINKS=file://$PIP_WHEEL_DIR
matrix:
  include:
    - env: TOXENV=docs
    - python: 3.5
      env: TOXENV=py35-2.2
    - python: 3.6
      env: TOXENV=py36-2.2
    - python: 3.6
      env: TOXENV=py36-3.0
    - python: 3.6
      env: TOXENV=py36-master
    - python: 3.7
      env: TOXENV=py37-2.2
    - python: 3.7
      env: TOXENV=py37-3.0
    - python: 3.7
      env: TOXENV=py37-master
    - python: 3.8
      env: TOXENV=py38-2.2
    - python: 3.8
      env: TOXENV=py38-3.0
    - python: 3.8
      env: TOXENV=py38-master
after_success: codecov
cache:
  directories:
    - $HOME/.wheels
